spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/computer
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # for development, set to validate in production
    show-sql: false
    properties:
      hibernate:
        format_sql: true # for development, set to false in production
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: ostapnote2@gmail.com
    password: #password
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    cache: false # for development, set to true in production
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    suffix: .ftl
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 1800
